name: SonarCloud
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  scan-all-packages:
    name: Scan code quality for both front and back
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - 
        name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - 
        name: Install dependencies
        working-directory: front
        run: npm ci
      - 
        name: Run frontend tests and generate coverage report
        run: npm test -- --watch=false --browsers=ChromeHeadless --code-coverage
        working-directory: front
      - 
        name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
      - 
        name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - 
        name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - 
        name: Build with Maven
        working-directory: ./back
        run: mvn clean package
      - 
        name: Scan with sonarcloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=Cojusnean_Gerez-un-projet-collaboratif-en-int-grant-une-demarche-CI-CD
            -Dsonar.organization=cojusnean
            -Dsonar.java.binaries=back/target/classes
