name: Run tests and generate reports
run-name: Run tests and generate coverage reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-with-coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [11]
        node-version: [20] 

    steps:
      - uses: actions/checkout@v4

        # Backend
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Build and test backend
        working-directory: back
        run: mvn test -B

      - name: Upload backend(JaCoCo) coverage report
        uses: actions/upload-artifact@v4
        with:
          name: back-coverage-report
          path: back/target/site/jacoco/

      # Frontend
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: front
        run: npm ci

      - name: Run test with coverage
        working-directory: front
        run: npm test -- --code-coverage --browsers=ChromeHeadless --watch=false

      - name: Upload frontend coverage results
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage-report
          path: front/coverage/bobapp/
